# Generated by Django 4.0.4 on 2022-04-27 15:12

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testInProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentUsername', models.CharField(max_length=200, null=True)),
                ('studentName', models.CharField(max_length=200, null=True)),
                ('testName', models.CharField(blank=True, max_length=200, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('studentAnswersReading', jsonfield.fields.JSONField(default={}, null=True)),
                ('studentAnswersWriting', jsonfield.fields.JSONField(default={}, null=True)),
                ('statusReading', models.CharField(blank=True, default='NO', max_length=3, null=True)),
                ('statusWriting', models.CharField(blank=True, default='NO', max_length=3, null=True)),
                ('timeLeftReading', models.CharField(blank=True, default='60', max_length=200, null=True)),
                ('timeLeftWriting', models.CharField(blank=True, default='60', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentUsername', models.CharField(max_length=200, null=True)),
                ('studentName', models.CharField(max_length=200, null=True)),
                ('testName', models.CharField(blank=True, max_length=200, null=True)),
                ('date_finished', models.DateTimeField(auto_now_add=True)),
                ('studentAnswersReading', jsonfield.fields.JSONField(default={}, null=True)),
                ('studentAnswersWriting', jsonfield.fields.JSONField(default={}, null=True)),
                ('numberCorrect', models.CharField(default='0', max_length=10, null=True)),
                ('scoreReading', models.CharField(default='200', max_length=3, null=True)),
                ('scoreWriting', models.CharField(default='200', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('answerKey', jsonfield.fields.JSONField(default={}, null=True)),
                ('questionType', jsonfield.fields.JSONField(default={}, null=True)),
                ('pdfLink', models.URLField(blank=True, default='https://i.postimg.cc/zftpFhs3/onwearcrop.png', max_length=250, null=True)),
            ],
        ),
    ]
