# Generated by Django 4.0.4 on 2022-05-04 03:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testspec',
            old_name='answerKey',
            new_name='answerKeyReading',
        ),
        migrations.RenameField(
            model_name='testspec',
            old_name='questionType',
            new_name='answerKeyWriting',
        ),
        migrations.AddField(
            model_name='testspec',
            name='questionTypeReading',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testspec',
            name='questionTypeWriting',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='testspec',
            name='pdfLink',
            field=models.URLField(blank=True, default='https://drive.google.com/file/d/14xUAfhLiG2AQR-jdNcjwT9ZYlA0ZaHZr/preview', max_length=250, null=True),
        ),
    ]
