# Generated by Django 4.0.4 on 2022-05-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0002_rename_answerkey_testspec_answerkeyreading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinprogress',
            name='studentId',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
