# Generated by Django 4.0.4 on 2022-05-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0003_testinprogress_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='testspec',
            name='pdfLink2',
            field=models.URLField(blank=True, default='https://drive.google.com/file/d/14xUAfhLiG2AQR-jdNcjwT9ZYlA0ZaHZr/preview', max_length=250, null=True),
        ),
    ]
