# Generated by Django 4.0.4 on 2022-05-07 05:29

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0004_testspec_pdflink2'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='jsonWrongQtypeR',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='jsonWrongQtypeW',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='numberInCorrect',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
    ]
