# Generated by Django 4.0.4 on 2022-05-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0005_testrecord_jsonwrongqtyper_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrecord',
            old_name='numberCorrect',
            new_name='numberInCorrectR',
        ),
        migrations.RenameField(
            model_name='testrecord',
            old_name='numberInCorrect',
            new_name='numberInCorrectW',
        ),
    ]
