# Generated by Django 4.0.4 on 2022-05-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0006_rename_numbercorrect_testrecord_numberincorrectr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='selectTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showTest', models.ManyToManyField(blank=True, to='cbtsystem.testspec')),
            ],
        ),
    ]
