# Generated by Django 4.0.4 on 2022-05-11 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0007_selecttest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='selectTest',
            new_name='setTest',
        ),
    ]
