# Generated by Django 4.0.4 on 2022-05-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0008_rename_selecttest_settest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='setTest',
            new_name='groupTest',
        ),
    ]
