# Generated by Django 4.0.4 on 2022-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0010_testinprogress_studentflagreading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinprogress',
            name='testId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='testId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
