# Generated by Django 4.0.4 on 2022-05-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0012_loggrecord_loggedinuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinprogress',
            name='timeLeftReading',
            field=models.CharField(blank=True, default='3610000', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testinprogress',
            name='timeLeftWriting',
            field=models.CharField(blank=True, default='3610000', max_length=200, null=True),
        ),
    ]
