# Generated by Django 4.0.4 on 2022-05-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0013_alter_testinprogress_timeleftreading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QtypeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='QtypeNotes Title', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, default='QtypeNotes Notes', null=True)),
            ],
        ),
    ]
