# Generated by Django 4.0.4 on 2022-08-23 15:02

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0015_testrecord_jsonqtypeperr_testrecord_jsonqtypeperw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='jsonQtypePerR',
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='jsonQtypePerW',
        ),
        migrations.AddField(
            model_name='testinprogress',
            name='statusMathOne',
            field=models.CharField(blank=True, default='NO', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='testinprogress',
            name='statusMathTwo',
            field=models.CharField(blank=True, default='NO', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='testinprogress',
            name='studentAnswersMathOne',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testinprogress',
            name='studentAnswersMathTwo',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testinprogress',
            name='studentFlagMathOne',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testinprogress',
            name='studentFlagMathTwo',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testinprogress',
            name='timeLeftMathOne',
            field=models.CharField(blank=True, default='3610000', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testinprogress',
            name='timeLeftMathTwo',
            field=models.CharField(blank=True, default='3610000', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='jsonQtypePerMathOne',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='jsonQtypePerMathTwo',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='jsonWrongQtypeMathOne',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='jsonWrongQtypeMathTwo',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='numberInCorrectM1',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='numberInCorrectM2',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='scoreMath',
            field=models.CharField(default='200', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='studentAnswersMathOne',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='studentAnswersMathTwo',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testspec',
            name='answerKeyMathOne',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testspec',
            name='answerKeyMathTwo',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testspec',
            name='pdfLinkMathOne',
            field=models.URLField(blank=True, default='https://drive.google.com/file/d/14xUAfhLiG2AQR-jdNcjwT9ZYlA0ZaHZr/preview', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='testspec',
            name='pdfLinkMathTwo',
            field=models.URLField(blank=True, default='https://drive.google.com/file/d/14xUAfhLiG2AQR-jdNcjwT9ZYlA0ZaHZr/preview', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='testspec',
            name='questionTypeMathOne',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testspec',
            name='questionTypeMathTwo',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
    ]
