# Generated by Django 4.0.4 on 2022-09-04 01:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0016_remove_testrecord_jsonqtypeperr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='jsonQtypePerR',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='jsonQtypePerW',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
    ]
