# Generated by Django 4.0.4 on 2022-11-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0017_testrecord_jsonqtypeperr_testrecord_jsonqtypeperw'),
    ]

    operations = [
        migrations.CreateModel(
            name='testDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_test', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
