# Generated by Django 4.0.4 on 2022-11-19 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0018_testdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdate',
            name='next_test',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
