# Generated by Django 4.0.4 on 2022-11-19 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0019_alter_testdate_next_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdate',
            name='next_test',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
