# Generated by Django 4.0.4 on 2022-12-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0021_testspec_studentresponseone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testspec',
            name='studentResponseOne',
            field=models.TextField(blank=True, default='12', null=True),
        ),
        migrations.AlterField(
            model_name='testspec',
            name='studentResponseTwo',
            field=models.TextField(blank=True, default='12', null=True),
        ),
    ]
