# Generated by Django 4.0.4 on 2022-12-11 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbtsystem', '0022_alter_testspec_studentresponseone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('signupdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('school', models.CharField(default='School Name', max_length=100, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=15, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('comment', models.TextField(blank=True, default='Write comments here.', null=True)),
                ('userAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
