# Generated by Django 4.0.4 on 2023-02-07 08:03

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cbtsystem', '0023_accountprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='showTest',
            field=models.ManyToManyField(blank=True, to='cbtsystem.testspec'),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testinprogress',
            name='studentFlagMathOne',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='testinprogress',
            name='studentFlagMathTwo',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='testinprogress',
            name='studentFlagReading',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='testinprogress',
            name='studentFlagWriting',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
